### ISSUE TITLE
Modelangelo env cannot access CUDA (installation issue?)

### ISSUE THREAD

**Issue by martin-s-a** [scipion-em/scipion-em-modelangelo#8]
Extracted from issue reported via Discord in channel #model-building.

```
└ <function _cuda_deserialize at 0x7fb5a7979f70>
00144:     File "/usr/local/scipion/conda/envs/modelangelo-git/lib/python3.9/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
00145:       device = validate_cuda_device(location)
00146:                │                    └ 'cuda:0'
00147:                └ <function validate_cuda_device at 0x7fb5a7979ee0>
00148:     File "/usr/local/scipion/conda/envs/modelangelo-git/lib/python3.9/site-packages/torch/serialization.py", line 166, in validate_cuda_device
00149:       raise RuntimeError('Attempting to deserialize object on a CUDA '
00150:   
00151:   RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
00152:   Traceback (most recent call last):
00153:     File "/usr/local/scipion/conda/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 201, in run
00154:       self._run()
00155:     File "/usr/local/scipion/conda/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 252, in _run
00156:       resultFiles = self._runFunc()
00157:     File "/usr/local/scipion/conda/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 248, in _runFunc
00158:       return self._func(*self._args)
00159:     File "/usr/local/scipion/conda/lib/python3.8/site-packages/modelangelo/protocols/protocol_model_angelo.py", line 140, in predictStep
00160:       raise ChildProcessError("Model angelo has failed: %s. See error log "
00161:   ChildProcessError: Model angelo has failed: RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.. See error log for more details.
00162:   Protocol failed: Model angelo has failed: RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.. See error log for more details.
```
Seems related to the enviroment `/usr/local/scipion/conda/envs/modelangelo-git`.
Running `conda list` returns the following:
```
# packages in environment at /usr/local/scipion/conda/envs/modelangelo-git:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
biopython                 1.81                     pypi_0    pypi
blas                      1.0                         mkl  
brotlipy                  0.7.0           py39h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.01.10           h06a4308_0  
certifi                   2022.12.7        py39h06a4308_0  
cffi                      1.15.1           py39h5eee18b_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
contourpy                 1.0.7                    pypi_0    pypi
cryptography              39.0.1           py39h9ce1e76_0  
cudatoolkit               11.3.1               h2bc3f7f_2  
cycler                    0.11.0                   pypi_0    pypi
einops                    0.6.0                    pypi_0    pypi
fair-esm                  2.0.0                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.9.0            py39h06a4308_0  
flit-core                 3.8.0            py39h06a4308_0  
fonttools                 4.39.2                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
giflib                    5.2.1                h5eee18b_3  
gmp                       6.2.1                h295c915_3  
gmpy2                     2.1.2            py39heeb90bb_0  
gnutls                    3.6.15               he1e5248_0  
idna                      3.4              py39h06a4308_0  
importlib-resources       5.12.0                   pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
jinja2                    3.1.2            py39h06a4308_0  
jpeg                      9e                   h5eee18b_1  
kiwisolver                1.4.4                    pypi_0    pypi
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libdeflate                1.17                 h5eee18b_0  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h7f8727e_2  
libidn2                   2.3.2                h7f8727e_0  
libpng                    1.6.39               h5eee18b_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.5.0                h6a678d5_2  
libunistring              0.9.10               h27cfd23_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
loguru                    0.6.0                    pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_0  
markupsafe                2.1.1            py39h7f8727e_0  
matplotlib                3.7.1                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
model-angelo              0.2.2                     dev_0    <develop>
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpmath                    1.2.1            py39h06a4308_0  
mrcfile                   1.4.3                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  2.8.4            py39h06a4308_1  
numpy                     1.24.2                   pypi_0    pypi
numpy-base                1.23.5           py39h31eccc5_0  
openh264                  2.1.1                h4ff587b_0  
openssl                   1.1.1t               h7f8727e_0  
packaging                 23.0                     pypi_0    pypi
pandas                    1.5.3                    pypi_0    pypi
pillow                    9.4.0                    pypi_0    pypi
pip                       23.0.1           py39h06a4308_0  
psutil                    5.9.4                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pyhmmer                   0.7.2                    pypi_0    pypi
pyopenssl                 23.0.0           py39h06a4308_0  
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.16               h7a1cb2a_2  
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   2.0.0               py3.9_cpu_0    pytorch
pytorch-mutex             1.0                         cpu    pytorch
pytz                      2022.7.1                 pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.28.1           py39h06a4308_1  
scipy                     1.10.1                   pypi_0    pypi
setuptools                65.6.3           py39h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.41.1               h5eee18b_0  
sympy                     1.11.1           py39h06a4308_0  
tk                        8.6.12               h1ccaba5_0  
torchaudio                2.0.0                  py39_cpu    pytorch
torchvision               0.15.0                 py39_cpu    pytorch
tqdm                      4.65.0                   pypi_0    pypi
typing_extensions         4.4.0            py39h06a4308_0  
tzdata                    2022g                h04d1e81_0  
urllib3                   1.26.14          py39h06a4308_0  
wheel                     0.38.4           py39h06a4308_0  
xz                        5.2.10               h5eee18b_1  
zipp                      3.15.0                   pypi_0    pypi
```
Tried running `conda install -c "nvidia/label/cuda-11.7.0" cuda-toolkit` with the enviroment activated, but did not solve the issue.
To test the accessibility of the pytorch package to CUDA, we activated the enviroment (`conda activate /usr/local/scipion/conda/envs/modelangelo-git`), launched the python terminal (`python3`), and ran the following code:
```
import torch
print(torch.__version__)
print(torch.cuda.is_available())
```
which returned:
```
import torch
>>> print(torch.version)
2.0.0
>>> print(torch.cuda.is_available())
False
>>>
```

**Comment by pconesa** [comment]
Try installing modelangelo manually outside scipion:

https://github.com/3dem/model-angelo

And then define MODEL_ANGELO_ACTIVATION to activate your "Manually created environment.

And see if it works. Maybe the automatic installation in your machine is somehow problematic

**Comment by azazellochg** [comment]
Hi, this should be fixed now once the opened PRs are merged.
